export const apiRoute = {
    login: 'http://localhost/Bhramanapp/Backend/server/auth/login.php',
    signup: 'http://localhost/Bhramanapp/Backend/server/auth/signup.php',
    logout: 'http://localhost/Bhramanapp/Backend/server/auth/logout.php',
    getUser: 'http://localhost/Bhramanapp/Backend/server/auth/get_user.php',
    getLocations: 'http://localhost/Bhramanapp/Backend/server/location/get_locations.php',
    getTopLocations: 'http://localhost/Bhramanapp/Backend/server/location/get_top_locations.php',
    getLocationDetail: 'http://localhost/Bhramanapp/Backend/server/location/get_locationDetail.php',
    addLocation: 'http://localhost/Bhramanapp/Backend/server/location/add_location.php',
    editLocation: 'http://localhost/Bhramanapp/Backend/server/location/edit_location.php',
    deleteLocation: 'http://localhost/Bhramanapp/Backend/server/location/delete_location.php',
    addRating: 'http://localhost/Bhramanapp/Backend/server/location/add_rating.php',
    addComment: 'http://localhost/Bhramanapp/Backend/server/Comment/add_comment.php',
    getComments: 'http://localhost/Bhramanapp/Backend/server/Comment/get_comment.php',
    manageBookings: 'http://localhost/Bhramanapp/Backend/server/booking/manage_bookings.php',
};